name: Latest blog post workflow

on:
  schedule:
    - cron: '0 * * * *' # Runs every hour, on the hour
  workflow_dispatch: # Run workflow manually

permissions:
  contents: write # To write the generated contents to the readme

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Download the XML file from the repository
      - name: Download XML file
        run: curl -sSL -o blog.xml "https://raw.githubusercontent.com/elifKALENDER/elifKALENDER/main/.github/assets/5776187_509.xml"

      - name: Pull in dev.to posts
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "file://blog.xml"
          #max_post_count: 15

